### ISSUE TITLE
create a module converting the solution obtained by the planner to a plan the robot can execute

### ISSUE THREAD

**Issue by Koldar** [STB1019/Robotieee#10]

**Comment by nicola-onofri** [comment]
.sol to JSON is done. Since I had no instructions about the structure of the file I came up with this:

* I've discarded the info about the computed solution (version, path, seed, mutex_time, ecc)
* Each instruction has been translated to a JSON element using the following template:
  - "action": type of action (move, push-to-goal, push-to-nongoal)
  - "player": name of the player
  - "stone": name of the stone (only in move instructions)
  - "player-starting-pos": a list containing 2 coordinates [x, _], [y,_]
  - "starting-pos": a list containing 2 coordinates [x, _], [y,_]
  - "final-pos": a list containing 2 coordinates [x, _], [y,_]
  - "direction": the direction of the move

Let me know if the structure has to be changed, that won't take much time anyway

**Comment by nicola-onofri** [comment]
Update: as I said in the last commit, I changed "pos" tags to JSON dictionaries instead of lists. It sounds better to me. That's all!
